services:
  authdb:
    container_name: auth-db
    image: bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=root
      - POSTGRESQL_DATABASE=authdb
    ports:
      - "5432:5432"
